<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Label="ExtraInformation">
    <Authors>RuoFan</Authors>
    <Product>RX-Explorer-WAS-PluginDefinition</Product>
    <PackageTags>RX-Explorer-WAS;RX-Explorer;Plugin</PackageTags>
    <AssemblyTitle>RX-Explorer-WAS-PluginDefinition</AssemblyTitle>
    <Copyright>RX-Explorer Developer. All rights reserved.</Copyright>
    <Description>Plugin definition for RX-Explorer (WAS)</Description>
    <RepositoryUrl>https://github.com/zhuxb711/RX-Explorer-WAS-PluginDefinition</RepositoryUrl>
    <PackageProjectUrl>https://github.com/zhuxb711/RX-Explorer-WAS-PluginDefinition</PackageProjectUrl>
  </PropertyGroup>
  <PropertyGroup Label="SourceLink" Condition="'$(Configuration)' == 'Release'">
    <IncludeSymbols>true</IncludeSymbols>
    <EmbedAllSources>true</EmbedAllSources>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.102" PrivateAssets="All" />
  </ItemGroup>
</Project>