<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
  	<Version>1.5.3</Version>
	<IncludeSymbols>true</IncludeSymbols>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<PackageId>RX-Explorer-WAS.PluginDefinition</PackageId>
    <RootNamespace>RX_Explorer_WAS.PluginDefinition</RootNamespace>
	<AssemblyName>RX-Explorer-WAS.PluginDefinition</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
	<None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
