name: Build CI Artifacts

on:
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  CIBuild:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      Env_Configuration: Release
      Env_SolutionPath: ${{github.workspace}}/RX-Explorer-WAS-PluginDefinition.slnx

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Install Latest .NET 10 SDK
        uses: actions/setup-dotnet@v5.4.0
        with:
          dotnet-version: 10.x

      - name: Build Plugin Definition Artifacts
        shell: pwsh
        run: |
          dotnet build "${{env.Env_SolutionPath}}" `
            --verbosity normal `
            --configuration ${{env.Env_Configuration}} `
            --property:ContinuousIntegrationBuild=true
