name: Publish Artifacts

on:
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  Publish:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      id-token: write
    env:
      Env_Configuration: Release
      Env_SolutionPath: ${{github.workspace}}/RX-Explorer-WAS-PluginDefinition.slnx
      Env_PublishOutputPath: ${{github.workspace}}/Output

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Install Latest .NET 10 SDK
        uses: actions/setup-dotnet@v6.0.0
        with:
          dotnet-version: 10.x

      - name: Build Plugin Definition Artifacts
        shell: pwsh
        run: |
          dotnet pack "${{env.Env_SolutionPath}}" `
            --verbosity normal `
            --output "${{env.Env_PublishOutputPath}}" `
            --configuration ${{env.Env_Configuration}} `
            --property:ContinuousIntegrationBuild=true

      - name: Login NuGet with OIDC
        uses: NuGet/login@v1
        id: login
        with:
          user: zhuxb711

      - name: Validate And Publish
        shell: pwsh
        run: |
          Write-Host "Starting package validation and publishing process..."
          Write-Host "Installing package validate tool..."

          dotnet tool install --global dotnet-validate --version 0.0.1-preview.537

          Write-Host "Package validation tool installed successfully."
          Write-Host "Searching for .nupkg files in the output directory..."

          $nupkgFiles = Get-ChildItem -Path "${{env.Env_PublishOutputPath}}" -Filter "*.nupkg"

          Write-Host "Found $($nupkgFiles.Count) .nupkg files."
          Write-Host "Including $([String]::Join(', ', '"' + $nupkgFiles.Name + '"'))"

          foreach ($file in $nupkgFiles) {
            Write-Host "Validating package `"$($file.Name)`""

            dotnet validate package local "$($file.FullName)"

            if ($LASTEXITCODE -ne 0) {
              Write-Error "Package `"$($file.Name)`" validation failed"
              exit $LASTEXITCODE
            }

            Write-Host "Package `"$($file.Name)`" validation passed."
            Write-Host "Publishing package `"$($file.Name)`" to NuGet.org using Trusted Publishing"

            dotnet nuget push "$($file.FullName)" --source "nuget" --api-key "${{steps.login.outputs.NUGET_API_KEY}}"

            if ($LASTEXITCODE -ne 0) {
              Write-Error "Failed to publish package `"$($file.Name)`" to NuGet.org"
              exit $LASTEXITCODE
            }
            
            Write-Host "Package `"$($file.Name)`" published to NuGet.org successfully."
          }

          Write-Host "All packages have been published to NuGet.org successfully."

      - name: Reserve Space And Cleanup Outdated Artifacts
        uses: zhuxb711/artifacts-size-based-cleanup-action@v1.3.0
        with:
          limit: 1.5GB
          failOnError: true
          removeDirection: oldest
          simulateCompressionLevel: 9
          artifactPaths: ${{env.Env_PublishOutputPath}}

      - name: Upload Plugin Definition Artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: Plugin Definition Artifacts
          compression-level: 9
          if-no-files-found: error
          path: ${{env.Env_PublishOutputPath}}
