name: Publish Artifacts

on:
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  Publish:
    runs-on: windows-latest
    permissions:
      actions: write
      contents: read
    env:
      Env_Configuration: Release
      Env_BuildToolArchitecture: x64
      Env_SolutionPath: ${{github.workspace}}\RX-Explorer-WAS-PluginDefinition.slnx
      Env_PublishOutputPath: ${{github.workspace}}\Output

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.0

      - name: Install Latest .NET 9 SDK
        uses: actions/setup-dotnet@v5.0.1
        with:
          dotnet-version: 9.x

      - name: Install Latest MSBuild Workload
        uses: microsoft/setup-msbuild@v2.0.0
        with:
          msbuild-architecture: x64

      - name: Build Plugin Definition Artifacts
        shell: pwsh
        run: |
          msbuild "${{env.Env_SolutionPath}}" `
            /m `
            /nr:false `
            /restore `
            /t:Clean,Pack `
            /p:Configuration="${{env.Env_Configuration}}" `
            /p:PackageOutputPath="${{env.Env_PublishOutputPath}}\" `
            /p:PreferredToolArchitecture="${{env.Env_BuildToolArchitecture}}" `

      - name: Reserve Space And Cleanup Outdated Artifacts
        uses: zhuxb711/artifacts-size-based-cleanup-action@v1.2.1
        with:
          limit: 1.5GB
          failOnError: true
          removeDirection: oldest
          simulateCompressionLevel: 9
          artifactPaths: ${{env.Env_PublishOutputPath}}

      - name: Upload Plugin Definition Artifacts
        uses: actions/upload-artifact@v5.0.0
        with:
          name: Plugin Definition Artifacts
          compression-level: 9
          if-no-files-found: error
          path: ${{env.Env_PublishOutputPath}}
