name: Build PR Artifacts

on:
  pull_request:
    branches: [master]

concurrency:
  group: ${{github.workflow}}-${{github.event.pull_request.number}}
  cancel-in-progress: true

jobs:
  PRBuild:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      Env_Configuration: Release
      Env_SolutionPath: ${{github.workspace}}/RX-Explorer-WAS-PluginDefinition.slnx

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Install Latest .NET 10 SDK
        uses: actions/setup-dotnet@v5.1.0
        with:
          dotnet-version: 10.x

      - name: Build Plugin Definition Artifacts
        shell: pwsh
        run: |
          dotnet build "${{env.Env_SolutionPath}}" `
            --configuration "${{env.Env_Configuration}}" `
            --property:ContinuousIntegrationBuild=true
