name: GitHub Actions Dependencies Updater

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  Maintenance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
        with:
          token: ${{secrets.WORKFLOW_SECRET}}

      - name: Run GitHub Actions Dependencies Updater
        uses: saadmk11/github-actions-version-updater@v0.8.1
        with:
          token: ${{secrets.WORKFLOW_SECRET}}
          commit_message: "Commit for GitHub Actions Dependencies Update"
          update_version_with: "release-tag"
          pull_request_title: "PR for Github Actions Dependencies Update"
          pull_request_labels: "Dependencies, Automated, Continuous Integration"
